<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-EmailService.Worker-b4f5f769-143d-4b3e-82ae-65c6d7e33f8a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Polly" Version="8.6.6" />
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmailService.Application\EmailService.Application.csproj" />
    <ProjectReference Include="..\EmailService.Infrastructure\EmailService.Infrastructure.csproj" />
    <ProjectReference Include="..\SharedContracts\SharedContracts.csproj" />
  </ItemGroup>
</Project>
